approvedGitRepositories:
  - '**'

checksumBehavior: update

enableScripts: true

nmHoistingLimits: workspaces

nodeLinker: node-modules

npmScopes:
  simonegauli:
    npmAlwaysAuth: true
    npmPublishRegistry: 'https://registry.npmjs.org'
    npmRegistryServer: 'https://registry.npmjs.org'
